[tool.briefcase]
project_name = "Wordle"
bundle = "personal.martirez.derrynjoi"
version = "0.0.1"
url = "https://derrynjoi.martirez.personal/wordle"
license = "MIT license"
author = 'Derryn Joi Martirez'
author_email = "derrynjm@gmail.com"

[tool.briefcase.app.wordle]
formal_name = "Wordle"
description = "Application based on the game Wordle"
icon = "src/wordle/resources/wordle"
sources = ['src/wordle']
requires = [
]


[tool.briefcase.app.wordle.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.wordle.linux]
requires = [
    'toga-gtk>=0.3.0.dev34',
]

[tool.briefcase.app.wordle.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.wordle.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.wordle.windows]
requires = [
    'toga-winforms>=0.3.0.dev34',
]

# Mobile deployments
[tool.briefcase.app.wordle.iOS]
requires = [
    'toga-iOS>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.wordle.android]
requires = [
    'toga-android>=0.3.0.dev34'
]
